_BASE_: ../Cityscapes-PanopticSegmentation/Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  # WEIGHTS: "././relations_output_seg_encoder_resnet101_new/model_best.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res5"]
    DEPTH: 101
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NUM_CLASSES: 133
    LOSS_TOP_K: 1.0
    USE_DEPTHWISE_SEPARABLE_CONV: True
    LOSS_WEIGHT: 2.0
  PANOPTIC_DEEPLAB:
    STUFF_AREA: 4096
    NMS_KERNEL: 41
    SIZE_DIVISIBILITY: 640
    USE_DEPTHWISE_SEPARABLE_CONV: True
    PREDICT_INSTANCES: True
  PSG_RELATION_ENCODER:
    ENCODER_DEPTH: 6
    TOTAL_RELATIONS: 56
    TOTAL_CLASSES: 133
    HEIGHT: 32
    WIDTH: 32
    NUM_HEADS: 2
    LOSS_WEIGHT: 1.0
    ALPHA: 1.0
DATASETS:
  TRAIN: ("psg_train",)
  TEST: ("psg_val",)
SOLVER:
  BASE_LR: 1e-4
  MAX_ITER: 40000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 1000
INPUT:
  FORMAT: "RGB"
  GAUSSIAN_SIGMA: 8
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 640) for x in range(5, 16)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 960
  MAX_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
OUTPUT_DIR: "./relations_output_seg_encoder_resnet101_2"
TEST:
  EVAL_PERIOD: 1000
  